# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Allow print statements for debugging
    avoid_print: false
    
    # Style rules (lenient)
    prefer_single_quotes: true
    camel_case_types: true
    camel_case_extensions: true
    non_constant_identifier_names: false  # Allow snake_case for simplicity
    
    # Error prevention
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    use_key_in_widget_constructors: true
    
    # Code quality (lenient)
    prefer_final_fields: false
    prefer_final_locals: false
    sort_constructors_first: false

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
