name: Flutter Web Deploy

on:
  push:
    branches: [main]

concurrency:
  group: pages
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.6"

      - name: Install dependencies
        working-directory: ./todo_app
        run: flutter pub get

      - name: Analyze
        working-directory: ./todo_app
        run: flutter analyze

      - name: Test
        working-directory: ./todo_app
        run: flutter test

      - name: Install Sentry CLI
        run: |
          curl -sL https://sentry.io/get-cli/ | bash

      - name: Create sentry.properties
        working-directory: ./todo_app
        run: |
          echo "auth_token=${{ secrets.SENTRY_AUTH_TOKEN }}" > sentry.properties
          echo "org=lviv-politechnic" >> sentry.properties
          echo "project=flutter" >> sentry.properties

      - name: Build Web with Sentry
        working-directory: ./todo_app
        run: |
          flutter build web --release --web-renderer html --base-href="/todo_app/" \
            --dart-define=SENTRY_DSN=${{ secrets.SENTRY_DSN }}

      - name: Create Sentry release
        working-directory: ./todo_app
        run: |
          sentry-cli releases new \
            --org lviv-politechnic \
            --project flutter \
            --version $(git rev-parse --short HEAD)

      - name: Upload sourcemaps to Sentry
        working-directory: ./todo_app
        run: |
          sentry-cli releases files \
            --org lviv-politechnic \
            --project flutter \
            --version $(git rev-parse --short HEAD) \
            --dist ./build/web \
            --url-prefix "/todo_app/"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: todo_app/build/web

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4